import { cn } from '@/lib/utils'

const assetPath = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\/+/, '')}`

// Brand badge: the nous-girl mark in the app-icon squircle, theme-aware —
// light mode shows the black girl on the white squircle, dark mode the white
// girl on the #0d1117 squircle. The mark PNG carries the rounded shape and
// transparent corners, so no tile/rounding classes here. Generated by
// scripts/generate_icons.py from the girl SVGs + squircle backgrounds; size
// via className (default size-14).
export function BrandMark({ className, ...props }: React.ComponentProps<'span'>) {

  return (
    <span className={cn('inline-flex size-14 shrink-0 items-center justify-center', className)} {...props}>
      <img alt="Actelyo" className="size-full object-contain" src={assetPath('actelyo-logo.png')} />
    </span>
  )
}
